#!/usr/bin/env python26
from subprocess import call, sys, os
from ansible.parsing.dataloader import DataLoader
from ansible.inventory import Inventory
from ansible.vars import VariableManager


def usage():
    prog = os.path.basename(__file__)
    sys.stderr.write('Usage: {0} HOSTPATTERN\n'.format(prog))
    sys.exit(1)


def get_hosts(pattern):
    loader = DataLoader()
    variable_manager = VariableManager()
    inventory = Inventory(loader=loader, variable_manager=variable_manager)
    return inventory.get_hosts(pattern=pattern)


def main(pattern='*', command=[]):
    hosts = get_hosts(pattern)

    if len(hosts) == 0:
        sys.stderr.write('No hosts found.\n')
        sys.exit(1)

    print '\n'.join(sorted([host.name for host in hosts]))


if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == '-h':
        usage()
    elif len(sys.argv) <> 2:
        usage()
    else:
        pattern = sys.argv[1]
        try:
            main(pattern, sys.argv[2:])
        except KeyboardInterrupt:
            pass
